#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 12 23:05:10 2019

@author: Alexander Aigner
"""

interventions = {}


interventions['314'] = [
        ('1899 Hoffenheim', 1),
        ('Werder Bremen', 4),
        ('Bor. Dortmund', 5),
        ('Mainz 05', 8),
        ('1. FC Union Berlin', 9),
        ('Werder Bremen', 10),
        ('SC Freiburg', 11),
        ('FC Augsburg', 13),
        ("Bor. M'Gladbach", 16),
        ('SC Paderborn', 17),
        ('Fortuna Düsseldorf', 18),
        ('Fortuna Düsseldorf', 18),
        ('Bor. Dortmund', 18),
        ('FC Augsburg', 18),
        ('Eintr. Frankfurt', 19),
        ('SC Paderborn', 19),
        ('SC Paderborn', 19),
        ('Fortuna Düsseldorf', 20),
        ('Fortuna Düsseldorf', 20),
        ('Fortuna Düsseldorf', 20),
        ('Hertha BSC', 22),
        ('1899 Hoffenheim', 23),
        ('SC Freiburg', 23),
        ('Schalke 04', 23),
        ('Fortuna Düsseldorf', 24),
        ('Bor. Dortmund', 27),
        ('RB Leipzig', 28),
        ('Fortuna Düsseldorf', 28),
        ('1899 Hoffenheim', 29),
        ('1899 Hoffenheim', 30),
        ('SC Paderborn', 31),
        ('Mainz 05', 31),
        ('FC Augsburg', 32),
        ('Schalke 04', 34)
        ]

interventions['311'] = [
        ('1899 Hoffenheim',1),
        ('Hertha BSC',1),
        ('VfL Wolfsburg',1),
        ('1899 Hoffenheim',4),
        ('Hertha BSC',4),
        ('RB Leipzig',4),
        ('1. FC Nürnberg',6),
        ('1. FC Nürnberg',6),
        ('1899 Hoffenheim',7),
        ('1899 Hoffenheim',7),
        ('Eintr. Frankfurt',8),
        ('1. FC Nürnberg',8),
        ('VfL Wolfsburg',9),
        ('Bor. Dortmund',10),
        ('VfB Stuttgart',11),
        ('Werder Bremen',12),
        ('Werder Bremen',13),
        ('1899 Hoffenheim',13),
        ('RB Leipzig',13),
        ('Hannover 96',14),
        ('Fortuna Düsseldorf',15),
        ('Hannover 96',15),
        ('RB Leipzig',16),
        ('VfB Stuttgart',17),
        ('Eintr. Frankfurt',17),
        ('Bor. Dortmund',19),
        ('Eintr. Frankfurt',19),
        ('Schalke 04',24),
        ('Schalke 04',24),
        ("Bor. M'Gladbach",24),
        ('1899 Hoffenheim',24),
        ('1. FC Nürnberg',25),
        ("Bor. M'Gladbach",27),
        ('Fortuna Düsseldorf',27),
        ('1. FC Nürnberg',27),
        ('FC Augsburg',27),
        ('VfL Wolfsburg',29),
        ('Eintr. Frankfurt',31),
        ("Bor. M'Gladbach",34)
        ]

interventions['307'] = [
        ('Werder Bremen',2),
        ('Bor. Dortmund',9),
        ('FC Augsburg',12),
        ('1899 Hoffenheim',12),
        ('Schalke 04',13),
        ('Bayer Leverkusen',13),
        ('RB Leipzig',15),
        ('FC Augsburg',15),
        ('1899 Hoffenheim',20),
        ('1. FC Köln',21),
        ('Hamburger SV',21),
        ('FC Augsburg',23),
        ('Hamburger SV',24),
        ('Hannover 96',26),
        ('Eintr. Frankfurt',27),
        ('1. FC Köln',29),
        ('FC Augsburg',29),
        ("Bor. M'Gladbach",30),
        ("Bor. M'Gladbach",30),
        ('Hertha BSC',31),
        ("Bor. M'Gladbach",32)
        ]

interventions['302'] = [
        ('Mainz 05',2),
        ('Bayern München',3),
        ('Hertha BSC',4),
        ('Bayern München',6),
        ('RB Leipzig',7),
        ('1899 Hoffenheim',8),
        ('RB Leipzig',8),
        ('1. FC Köln',9),
        ('1. FC Köln',11),
        ('Hertha BSC',13),
        ('FC Ingolstadt',16),
        ('Werder Bremen',18),
        ('Werder Bremen',18),
        ('Hertha BSC',18),
        ('Bor. Dortmund',18),
        ('Mainz 05',19),
        ('Schalke 04',19),
        ('FC Ingolstadt',23),
        ('1899 Hoffenheim',23),
        ('RB Leipzig',27),
        ('Bor. Dortmund',28),
        ('Bor. Dortmund',28),
        ('SV Darmstadt 98',28),
        ('FC Augsburg',29),
        ('Mainz 05',30),
        ('1899 Hoffenheim',32),
        ('Werder Bremen',34),
        ('Bor. Dortmund',34)
        ]

interventions['205'] = [
        ('1899 Hoffenheim',1),
        ('Bayer Leverkusen',1),
        ('Hannover 96',1),
        ('1899 Hoffenheim',2),
        ('Eintr. Frankfurt',3),
        ('1899 Hoffenheim',3),
        ('Werder Bremen',3),
        ('Hertha BSC',5),
        ('Hamburger SV',6),
        ('FC Augsburg',6),
        ('VfB Stuttgart',7),
        ('Hannover 96',12),
        ('1899 Hoffenheim',16),
        ('Eintr. Frankfurt',18),
        ('Bayer Leverkusen',21),
        ('FC Augsburg',25),
        ('Hertha BSC',27),
        ('SV Darmstadt 98',29)
        ]

interventions['202'] = [
        ('Eintr. Frankfurt',2),
        ('1899 Hoffenheim',2),
        ('1899 Hoffenheim',2),
        ('SC Freiburg',2),
        ('Mainz 05',4),
        ('Bayer Leverkusen',4),
        ('SC Paderborn',7),
        ('SC Freiburg',7),
        ('SC Freiburg',9),
        ('Bor. Dortmund',9),
        ("Bor. M'Gladbach",9),
        ('Hamburger SV',10),
        ('VfL Wolfsburg',13),
        ('SC Freiburg',14),
        ('Bor. Dortmund',21),
        ('Hannover 96',28),
        ('VfB Stuttgart',28),
        ('Mainz 05',28),
        ('Hamburger SV',29),
        ('SC Paderborn',30),
        ('Bayern München',31),
        ('Bayern München',32),
        ('1. FC Köln',32),
        ('Mainz 05',33),
        ('1. FC Köln',34)
        ]

interventions['93'] = [
        ('FC Augsburg',2),
        ('Bor. Dortmund',2),
        ('Hannover 96',3),
        ('VfB Stuttgart',3),
        ('1. FC Nürnberg',7),
        ('Hannover 96',8),
        ('Werder Bremen',8),
        ('1. FC Nürnberg',10),
        ('Bayern München',12),
        ('Werder Bremen',12),
        ('1. FC Nürnberg',12),
        ('VfL Wolfsburg',15),
        ('Braunschweig',19),
        ('FC Augsburg',22),
        ('1899 Hoffenheim',23),
        ('VfL Wolfsburg',24),
        ('Bayer Leverkusen',31),
        ('Hamburger SV',32)
        ]

interventions['89'] = [
        ("Bor. M'Gladbach",4),
        ('VfL Wolfsburg',5),
        ('Bor. Dortmund',7),
        ('Hannover 96',12),
        ('Eintr. Frankfurt',12),
        ('Hamburger SV',15),
        ('Eintr. Frankfurt',17),
        ('Schalke 04',18),
        ('VfB Stuttgart',19),
        ('Fortuna Düsseldorf',19),
        ('Bor. Dortmund',21),
        ('VfL Wolfsburg',21),
        ('VfB Stuttgart',23),
        ('Fortuna Düsseldorf',24),
        ('Schalke 04',25),
        ('1899 Hoffenheim',29),
        ('VfB Stuttgart',29),
        ('1899 Hoffenheim',32),
        ('VfL Wolfsburg',32),
        ('Bayern München',33)
        ]

interventions['86'] = [
        ('SC Freiburg',3),
        ('Hamburger SV',5),
        ('Werder Bremen',7),
        ('Mainz 05',7),
        ('Bayern München',8),
        ('VfL Wolfsburg',10),
        ('VfL Wolfsburg',11),
        ('VfL Wolfsburg',12),
        ('Bayer Leverkusen',12),
        ('Bayern München',13),
        ('Mainz 05',14),
        ('VfB Stuttgart',16),
        ('Hamburger SV',17),
        ('Hamburger SV',19),
        ('Bor. Dortmund',20),
        ('FC Augsburg',20),
        ('VfB Stuttgart',21),
        ('Hannover 96',23),
        ('FC Augsburg',24),
        ('FC Augsburg',29),
        ('Mainz 05',30),
        ('1899 Hoffenheim',30),
        ('1. FC K´lautern',31)
        ]

interventions['83'] = [
        ('SC Freiburg',2),
        ('1899 Hoffenheim',4),
        ('Mainz 05',5),
        ('1. FC K´lautern',8),
        ('1. FC Nürnberg',9),
        ('1. FC Nürnberg',12),
        ('Mainz 05',16),
        ('Bayern München',17),
        ('1899 Hoffenheim',19),
        ('Hannover 96',23),
        ('Mainz 05',27),
        ('VfL Wolfsburg',27),
        ('Mainz 05',29)
        ]

interventions['80'] = [
        ('Mainz 05',3),
        ('VfL Wolfsburg',6),
        ('SC Freiburg',8),
        ('VfL Wolfsburg',11),
        ('Hamburger SV',21),
        ('VfL Wolfsburg',21),
        ('VfL Wolfsburg',28),
        ('VfB Stuttgart',32)
        ]

interventions['315'] = [
        ('VfL Bochum', 2),
        ('Greuther Fürth', 7),
        ('Karlsruher SC', 10),
        ('Hannover 96', 12),
        ('VfB Stuttgart', 15),
        ('VfB Stuttgart', 16),
        ('Dynamo Dresden', 18),
        ('Greuther Fürth', 18),
        ('Holstein Kiel', 19),
        ('VfB Stuttgart', 21),
        ('VfB Stuttgart', 22),
        ('VfB Stuttgart', 23),
        ('Wehen Wiesbaden', 26),
        ('Hamburger SV', 28),
        ('VfB Stuttgart', 28),
        ('VfL Osnabrück', 28),
        ('FC St. Pauli', 29),
        ('Holstein Kiel', 30),
        ('Hamburger SV', 30),
        ('SV Sandhausen', 30),
        ('SV Sandhausen', 31),
        ('VfL Osnabrück', 33),
        ('SV Darmstadt 98', 34),
        ('Hamburger SV', 34),
        ('SV Sandhausen', 34)
        ]

interventions['312'] = [
        ('MSV Duisburg',3),
        ('SV Darmstadt 98',3),
        ('FC Ingolstadt',3),
        ('Jahn Regensburg',4),
        ('MSV Duisburg',6),
        ('Erzgebirge Aue',6),
        ('Jahn Regensburg',7),
        ('FC St. Pauli',7),
        ('Greuther Fürth',7),
        ('1. FC Köln',8),
        ('1. FC Union Berlin',8),
        ('FC Ingolstadt',8),
        ('1. FC Union Berlin',8),
        ('Jahn Regensburg',11),
        ('Jahn Regensburg',11),
        ('Holstein Kiel',11),
        ('Jahn Regensburg',12),
        ('Dynamo Dresden',14),
        ('FC Ingolstadt',16),
        ('SV Darmstadt 98',16),
        ('1. FC Köln',16),
        ('FC Ingolstadt',17),
        ('FC St. Pauli',19),
        ('1. FC Heidenheim',21),
        ('1. FC Köln',24),
        ('VfL Bochum',28),
        ('VfL Bochum',28),
        ('Greuther Fürth',28),
        ('SV Darmstadt 98',28),
        ('Dynamo Dresden',29),
        ('SV Sandhausen',30),
        ('MSV Duisburg',30),
        ('Arminia Bielefeld',30),
        ('Holstein Kiel',31),
        ('Arminia Bielefeld',31),
        ('1. FC Heidenheim',32),
        ('SV Sandhausen',32),
        ('Jahn Regensburg',32),
        ('Erzgebirge Aue',32)
        ]

interventions['308'] = [
        ('1. FC Union Berlin',1),
        ('VfL Bochum',1),
        ('VfL Bochum',1),
        ('FC St. Pauli',1),
        ('Jahn Regensburg',2),
        ('Braunschweig',6),
        ('Braunschweig',6),
        ('Braunschweig',6),
        ('1. FC Heidenheim',6),
        ('Fortuna Düsseldorf',8),
        ('Greuther Fürth',8),
        ('1. FC Heidenheim',13),
        ('Holstein Kiel',14),
        ('Holstein Kiel',16),
        ('Braunschweig',17),
        ('1. FC Union Berlin',19),
        ('1. FC Union Berlin',20),
        ('Holstein Kiel',20),
        ('SV Darmstadt 98',20),
        ('FC St. Pauli',23),
        ('1. FC Nürnberg',23),
        ('Jahn Regensburg',24),
        ('SV Darmstadt 98',24),
        ('Arminia Bielefeld',26),
        ('VfL Bochum',27),
        ('1. FC Union Berlin',28),
        ('SV Darmstadt 98',28),
        ('1. FC Nürnberg',29),
        ('Holstein Kiel',30),
        ('Holstein Kiel',31),
        ('MSV Duisburg',32),
        ('Holstein Kiel',33),
        ('1. FC K´lautern',33),
        ('VfL Bochum',34),
        ('1. FC Nürnberg',34)
        ]

interventions['303'] = [
        ('Fortuna Düsseldorf',1),
        ('Karlsruher SC',1),
        ('VfB Stuttgart',1),
        ('VfB Stuttgart',1),
        ('FC Würzburger Kickers',3),
        ('FC Würzburger Kickers',4),
        ('Arminia Bielefeld',5),
        ('Hannover 96',6),
        ('Dynamo Dresden',7),
        ('FC St. Pauli',8),
        ('Arminia Bielefeld',8),
        ('Arminia Bielefeld',8),
        ('VfB Stuttgart',11),
        ('FC Würzburger Kickers',13),
        ('1. FC Heidenheim',14),
        ('1. FC Heidenheim',15),
        ('Fortuna Düsseldorf',15),
        ('VfL Bochum',16),
        ('SV Sandhausen',17),
        ('1860 München',18),
        ('FC St. Pauli',19),
        ('Dynamo Dresden',21),
        ('Dynamo Dresden',22),
        ('Erzgebirge Aue',22),
        ('Fortuna Düsseldorf',22),
        ('Fortuna Düsseldorf',23),
        ('FC St. Pauli',23),
        ('1. FC Heidenheim',23),
        ('1. FC Heidenheim',25),
        ('Braunschweig',25),
        ('FC St. Pauli',25),
        ('Erzgebirge Aue',25),
        ('Braunschweig',30),
        ('1. FC K´lautern',32),
        ('Fortuna Düsseldorf',32)
        ]

interventions['206'] = [
        ('SC Freiburg',2),
        ('SV Sandhausen',9),
        ('SC Paderborn',14),
        ('SV Sandhausen',15),
        ('Arminia Bielefeld',15),
        ('FSV Frankfurt',15),
        ('RB Leipzig',16),
        ('Braunschweig',16),
        ('Greuther Fürth',18),
        ('Braunschweig',25),
        ('SC Freiburg',27)
        ]

interventions['203'] = [
        ('FC St. Pauli',1),
        ('Erzgebirge Aue',4),
        ('Erzgebirge Aue',7),
        ('Fortuna Düsseldorf',7),
        ('FC St. Pauli',8),
        ('1. FC Union Berlin',13),
        ('1. FC Union Berlin',13),
        ('Fortuna Düsseldorf',15),
        ('SV Darmstadt 98',19),
        ('SV Darmstadt 98',19),
        ('RB Leipzig',19)
        ]

interventions['97'] = [
        ('Erzgebirge Aue',1),
        ('Erzgebirge Aue',1),
        ('Dynamo Dresden',2),
        ('FSV Frankfurt',2),
        ('SV Sandhausen',5),
        ('FC Ingolstadt',5),
        ('Dynamo Dresden',7),
        ('1860 München',8),
        ('FC Ingolstadt',15),
        ('Erzgebirge Aue',15),
        ('VfR Aalen',16),
        ('Erzgebirge Aue',16),
        ('SC Paderborn',22),
        ('VfR Aalen',22),
        ('VfR Aalen',22),
        ('Karlsruher SC',22),
        ('1. FC Köln',26),
        ('SC Paderborn',27),
        ('Energie Cottbus',29),
        ('Fortuna Düsseldorf',29),
        ('SV Sandhausen',30),
        ('1. FC Köln',30),
        ('1860 München',31),
        ('SC Paderborn',33)
        ]
